# Configuration defaults

CAMERA_INDEX = 0
FRAME_WIDTH = 960
FRAME_HEIGHT = 540
POSE_MIN_DET_CONF = 0.5
POSE_MIN_TRACK_CONF = 0.5
POSE_MODEL_COMPLEXITY = 1
VISIBILITY_THRESHOLD = 0.5
SEGMENTATION_THRESHOLD = 0.2
DEFAULT_MODE = "warp"  # "warp" or "bbox"
DEFAULT_UPPER_SCALE = 1.0
DEFAULT_LOWER_SCALE = 1.0
UPPER_WIDTH_PAD = 0.25
UPPER_HEIGHT_PAD_TOP = 0.25
UPPER_HEIGHT_PAD_BOTTOM = 0.10
LOWER_WIDTH_PAD = 0.25
LOWER_HEIGHT_PAD_TOP = 0.05
LOWER_HEIGHT_PAD_BOTTOM = 0.10

# Outfit anchor points in source images (fractions of width/height)
UPPER_SRC_LEFT_SHOULDER = (0.20, 0.18)
UPPER_SRC_RIGHT_SHOULDER = (0.80, 0.18)
UPPER_SRC_LEFT_HIP = (0.20, 0.96)

LOWER_SRC_LEFT_HIP = (0.20, 0.05)
LOWER_SRC_RIGHT_HIP = (0.80, 0.05)
LOWER_SRC_LEFT_ANKLE = (0.20, 0.96)

# Body-relative offsets for warp targets
UPPER_SHOULDER_OFFSET = -0.05
UPPER_HIP_OFFSET = 1.05
LOWER_HIP_OFFSET = 0.02
LOWER_ANKLE_OFFSET = 1.05
